### ISSUE TITLE
Over-head chat stays even when a person isn't typing.

### ISSUE THREAD

**Issue by NanoAi** [PAC3-Server/notagain#100]
Sometimes the over-head chat stays even if a player isn't typing. 
![example](https://user-images.githubusercontent.com/3096584/26903914-7cab6b44-4bad-11e7-987b-05849e94ba52.png)

It also clips into the player if a client has PAC disabled, if the players PAC happens to alter their height but that's a different issue.

**Comment by Techbot121** [comment]
it's something chat-related afaik

this happened as soon as we got rid of xp-chat.

I think @ToastyEngineer had an idea what caused it.

**Comment by Myaats** [comment]
I guess it's the FinishChat hook thats not being called in some way

**Comment by Earu** [comment]
It's not finishchat since I call it in EasyChat

**Comment by Earu** [comment]
for the reference look at lua/easychat/easychat.lua in function EasyChat.Close

**Comment by Myaats** [comment]
It might be ChatTextChanged being called after FinishChat after checking the code

**Comment by Myaats** [comment]
probably fixed with https://github.com/PAC3-Server/EasyChat/commit/0b4ef7b0e2c11e8a043ec1e59a97855eb63e8d65

re-open the issue if this persists
