### ISSUE TITLE
Votes for kicks (maybe bans?) and general votes

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#101]
UI for votes, ie votekicks and votebans maybe. Also the possibility to create votes with custom choices and question.

**Comment by CapsAdmin** [comment]
It shouldn't be too easy to vote. During a vote you should be asked if you want to participate and if you do you'll get a modal menu with all the choices.

**Comment by Zeni44** [comment]
https://github.com/notcake/gvote
meme

**Comment by Earu** [comment]
doesnt work too well but its there
