### ISSUE TITLE
change to random map if server is empty and allow players to vote change for map

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#102]
Change to a random map if the server player count is 0.

**Comment by Earu** [comment]
Im not too fan of this idea, maybe just wait for the player to have a vote system to vote for maps.

**Comment by NanoAi** [comment]
I feel that we should have a lobby map that the server goes to and then as people join they can vote to change the map to something else?

**Comment by Earu** [comment]
Yeah that sounds good to me

**Comment by Zeni44** [comment]
But what would the lobby map be or who would make one

**Comment by CapsAdmin** [comment]
I don't want a custom default map because I don't want to code something that works for that map only. I believe we shouldn't be too tied to a single map.

**Comment by Earu** [comment]
@CapsAdmin I understand your point but that prevents lots of things from being done

-> I already explained why, and how on discord. And as I said we should if not a default map, have a preset of maybe 5 maps maximum, so we can tie stuff to each map in that preset. Because switching everytime to maps without any preset defined, just prevent us from being effective with what we do, I mentionned the example of maybe 2d3d fix stuff like screens that would be impossible to do if we don't have at least a preset of maps.

**Comment by CapsAdmin** [comment]
Sure we don't need to shuffle between 100 maps. Maybe 5 of what we have atm are interesting.

**Comment by NanoAi** [comment]
Maybe get the top 5 most popular maps (that are also relevant for the
server)? I still think picking a good map to use as a lobby of sorts would
be very interesting, and that doesn't mean you have to code stuff specific
to that map either.

**Comment by CapsAdmin** [comment]
I'm fine with adding custom maps and coding for those custom maps. I just don't want us to be tied to one map.

It's kind of like having things more modular I guess

**Comment by Earu** [comment]
Sure, ill make a "framework" for it. 
Basically an autoloader that will load base classes, then you'll be able to derive those base classes, and will just have to define poses and angles for each maps for each "fixed" ent you made

**Comment by Earu** [comment]
im guessing votemap will solve this? (reopen if needed)
