### ISSUE TITLE
Various suggestions / issues / bugs (avernakis)

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#105]
- [ ] we need smoler variants of jiggles
- [ ] ui popup when you get levels to add points in mana/stamina etc..
- [ ] potions make white playermodels / pacs in some cases
- [x] rpg hud overlaps chathud
- [ ] rpg mode makes custom anims fuck up
- [ ] health bars disapear even when at a close distance to target
- [ ] magic weapon anim on idle needs to be looped correctly and slower
- [ ] new abilities in rpg mode (ie different than magic)
- [ ] "the targetting needs adjustment
should aim at what's in within your aim fov
like if i'm looking at grigori
i shouldn't fucking target someone behind me"
- [x] "my alt key makes the thing wielded properly
not in rpg
but in rpg mode
it doesn't work"

**Comment by nerdkoopa** [comment]
The server could use these two tools for building:
Multi-Parent / Unparent http://steamcommunity.com/sharedfiles/filedetails/?id=111929524
Make Spherical http://steamcommunity.com/sharedfiles/filedetails/?id=136318146
