### ISSUE TITLE
MapDefine usage(theming)

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#111]
In function of the area a player is, play ambience sounds (maybe music in certain cases ? with a convar to disable them), have graphical effects, maybe blossom trees leaves falling like snow? In caves spooky sounds and maybe evil laughs, screen borders are slighty dark? That kind of thing.

**Comment by NanoAi** [comment]
I can probably do that, seems like it'll be fun to make.

**Comment by NanoAi** [comment]
Update: Working on this and much more!
