### ISSUE TITLE
ChatHUD issues

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#117]
Issues that are yet to fix on chathud:

- [x] When a word/string is too long it overlaps
- [x] Color parsing/attribution is wrong
- [x] Tags Stopper method doesnt seem to work for most tags like rotate,size etc..
- [x] Chathud goes up for each message that fades out

**Comment by CapsAdmin** [comment]
Didn't you just fix the color thing?

**Comment by CapsAdmin** [comment]
Done

**Comment by CapsAdmin** [comment]
ops wrong issue

**Comment by CapsAdmin** [comment]
- [x] Space characters and newlines are being wrapped.

**Comment by CapsAdmin** [comment]
My word wrapping method doesn't seem to work well with long lines that have no space. I want to implement a proper one somehow but it's not that easy I think. 

Also in goluwa the chathud doesn't go up after fading out so I'm not sure what went wrong here.

**Comment by Earu** [comment]
probably your drawing method, you're removing the element of the table at fading i think, so it just removes all the spacing? im assuming

**Comment by CapsAdmin** [comment]
I've rewritten the wrapping method. This method will also stretch whitespace in an attempt to make things fit more neatly. This can be undesired in some cases but we'll see.

**Comment by CapsAdmin** [comment]
I've fixed the tag stopper thing now.

**Comment by CapsAdmin** [comment]
I've made it not go up after fade by always placing it at the center of chathud based on its height. This seems like a good solution but we'll see how it works in practice.
