### ISSUE TITLE
Scoreboard layout/info rewrite

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#121]
Because we noticed that even if its nice its not adapted when above 5 players are on

**Comment by NanoAi** [comment]
Looks like the scoreboard still runs a little too soon, the visuals work just fine however...
```
[ERROR] lua/notagain/jrpg/autorun/client/scoreboard.lua:163: attempt to call method 'SteamID' (a nil value)
  1. unknown - lua/notagain/jrpg/autorun/client/scoreboard.lua:163
```
Running the exact same code again on myself fixed the issue, however.

**Comment by Earu** [comment]
this is fixed, i just need to add jrpg infos stuff but graphically i have no idea how i want it to look like

**Comment by Earu** [comment]
done
