### ISSUE TITLE
List of UIs to finish/do

### ISSUE THREAD

**Issue by Earu** [PAC3-Server/notagain#124]
- [ ] AowlGUI
- [ ] Death Notifications https://gist.github.com/LuaTenshi/b4af3cebfd728a4e27d09ec0a3a0481c
- [ ] LevelingUp UI
- [x] Achievements UI
- [ ] HUD Redesign/Rewrite

**Comment by NanoAi** [comment]
I feel like the current HUD is nice for RPG. But it's kinda bulky and in the way when it comes to normal sandbox. I was thinking of replacing it with something small and not in the way.
