### ISSUE TITLE
Wanted: New Simple PropProtection replacing FPP

### ISSUE THREAD

**Issue by Techbot121** [PAC3-Server/notagain#130]
FPP seems to break a lot and needs to be replaced. 

Doesn't have to be feature rich or something since people doesn't build that often, but it would be nice if the cppi interface is supported (you have to anyway)

http://ulyssesmod.net/archive/CPPI_v1-3.pdf

**Comment by CapsAdmin** [comment]
Maybe we can just write it ourselves. I belive FPP is written with roleplaying in mind.

https://github.com/Donkie/SimplePropProtection seems alright, at least as a base.

I've been wanting to have a way to set friends and whatnot on the server as well and have it permanently stored. This could work well with a simple prop protection.

**Comment by NanoAi** [comment]
Is this done?

**Comment by CapsAdmin** [comment]
yes
