### ISSUE TITLE
Sanitize_prop_spawn 1 removes all overlapping props even when non-solid, frozen or parented.

### ISSUE THREAD

**Issue by nerdkoopa** [PAC3-Server/notagain#148]
Sanitize_prop_spawn 1 removes all overlapping props in dupes, even when they are frozen, nocollided, non-solid or parented. This makes it impossible to spawn any duplications with any level of overlapping pieces at all in any method, which is 99% of all Gmod creations ever.

**Comment by CapsAdmin** [comment]
fixed i think?
