### ISSUE TITLE
Couldn't find surface in GetColorForSurface()

### ISSUE THREAD

**Issue by NanoAi** [PAC3-Server/notagain#86]
When crashing into a wall and triggering the rockfall_death effect, allot of the time the console would get spammed with... Couldn't find surface in GetColorForSurface()

Not really sure what's causing this as here... https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/c_impact_effects.cpp#L120 it shows that the colour is reset back to white if that error happens however the colour does work and go through properly.

I guess you could fix it by removing `render.GetSurfaceColor(trace.HitPos + normal, trace.HitPos + (normal * -100))` but then it doesn't look as nice.

**Comment by CapsAdmin** [comment]
developer 0?

**Comment by NanoAi** [comment]
Yes that's set to 0 and I still get those notifications, not sure if this only happens on a LAN Server though as I can only run a LAN Server currently.

**Comment by CapsAdmin** [comment]
I think I've seen it but only under some circumstances I can't remember. It was either if developer was set to above 0 or maybe singleplayer or something.

You could have an additional check to make sure the trace hits something but I would argue this is an issue an issue with gmod.
