### ISSUE TITLE
Custom Death Notifications

### ISSUE THREAD

**Issue by Techbot121** [PAC3-Server/notagain#98]
jrpg style death notifications are still missing.

[insert some inspirational pictures here]

**Comment by NanoAi** [comment]
I'm thinking of using the assets from the HP bar and creating death notifications using those. Because we really do need to unify themes.

**Comment by NanoAi** [comment]
I've decided to make a more universal death notification system it's not really JRPG as I don't know how a JRPG death notification would even look like but I think it's better then nothing.

https://gist.github.com/LuaTenshi/b4af3cebfd728a4e27d09ec0a3a0481c

Looking for some help with actually drawing everything. 😢

**Comment by Earu** [comment]
forwarded to issue#124 in notagain
